const translations = {
  et: {
    common: [
      ["Skip to content", "Liigu sisu juurde"],
      ["Vooglin home", "Vooglini avaleht"],
      ["Primary navigation", "Põhinavigatsioon"],
      ["Mobile navigation", "Mobiilinavigatsioon"],
      ["Language", "Keel"],
      ["Services", "Teenused"],
      ["How it works", "Kuidas see töötab"],
      ["Pricing", "Hinnad"],
      ["About", "Meist"],
      ["Contact", "Kontakt"],
      ["Menu", "Menüü"],
      ["Close", "Sulge"],
      ["Practical automation and digital workflows for small organisations and project teams.", "Praktiline automatiseerimine ja digitaalsed töövood väikestele organisatsioonidele ja projektitiimidele."],
      ["All rights reserved.", "Kõik õigused kaitstud."],
      ["Back to top", "Tagasi üles"],
    ],
    home: [
      ["Vooglin — Practical automation for everyday work", "Vooglin — Praktiline automatiseerimine igapäevatööks"],
      ["Vooglin builds practical automation and digital workflows for small organisations, project teams, and growing businesses.", "Vooglin loob praktilisi automatiseerimislahendusi ja digitaalseid töövooge väikestele organisatsioonidele, projektitiimidele ja kasvavatele ettevõtetele."],
      ["Automate the work that slows you down.", "Automatiseeri töö, mis sind aeglustab."],
      ["Practical automation and digital workflows for small organisations and project teams.", "Praktiline automatiseerimine ja digitaalsed töövood väikestele organisatsioonidele ja projektitiimidele."],
      ["Discuss your workflow", "Räägime sinu töövoost"],
      ["Practical automation for small teams", "Praktiline automatiseerimine väikestele tiimidele"],
      ["Vooglin turns forms, spreadsheets, emails and documents into clear workflows that run with less manual effort.", "Vooglin muudab vormid, tabelid, e-kirjad ja dokumendid selgeteks töövoogudeks, mis vajavad vähem käsitööd."],
      ["An example Vooglin workflow", "Vooglini töövoo näide"],
      ["A typical workflow", "Tüüpiline töövoog"],
      ["Connected", "Ühendatud"],
      ["Collect", "Kogu"],
      ["Forms, email and files", "Vormid, e-post ja failid"],
      ["Organise", "Korrasta"],
      ["Rules, ownership and status", "Reeglid, vastutus ja olek"],
      ["Act", "Tegutse"],
      ["Documents, reminders and tasks", "Dokumendid, meeldetuletused ja ülesanded"],
      ["See", "Vaata"],
      ["Dashboards, reports and next steps", "Töölauad, aruanded ja järgmised sammud"],
      ["One workflow. Fewer handovers.", "Üks töövoog. Vähem üleandmisi."],
      ["Built for small organisations, project teams, events and growing businesses.", "Loodud väikestele organisatsioonidele, projektitiimidele, sündmustele ja kasvavatele ettevõtetele."],
      ["Based in Estonia · Working digitally", "Asume Eestis · Töötame digitaalselt"],
      ["A simpler way to work", "Lihtsam viis töötada"],
      ["Built around your process.<br>Not around a platform.", "Loodud sinu protsessi,<br>mitte platvormi ümber."],
      ["We find the repeated steps, connect the tools you already use, and build only what the work needs.", "Leiame korduvad sammud, ühendame tööriistad, mida juba kasutad, ja loome ainult selle, mida töö tegelikult vajab."],
      ["How Vooglin works", "Kuidas Vooglin töötab"],
      ["Practical by design", "Praktiline algusest peale"],
      ["Every part of the system has a clear job.", "Igal süsteemi osal on selge ülesanne."],
      ["Easy to understand", "Lihtne mõista"],
      ["Your team can see how it works and use it with confidence.", "Sinu tiim näeb, kuidas süsteem töötab, ja saab seda kindlalt kasutada."],
      ["Ready to improve", "Valmis arenema"],
      ["Start with the useful core, then grow it when the work changes.", "Alustame kasulikust põhjast ja arendame seda koos töö muutumisega."],
      ["Systems that remove repetitive work.", "Süsteemid, mis vähendavad korduvat tööd."],
      ["From one troublesome process to a connected day-to-day system.", "Ühest tülikast protsessist ühendatud igapäevase süsteemini."],
      ["Workflow automation<br>& integrations", "Töövoogude automatiseerimine<br>ja integratsioonid"],
      ["Connect forms, spreadsheets, email, documents and task tools into one reliable flow.", "Ühendame vormid, tabelid, e-posti, dokumendid ja ülesannete tööriistad üheks usaldusväärseks töövooks."],
      ["Forms, registrations<br>& events", "Vormid, registreerimised<br>ja sündmused"],
      ["Collect applications, manage limits and statuses, and send confirmations and reminders automatically.", "Kogume taotlused, haldame piirmäärasid ja olekuid ning saadame kinnitused ja meeldetuletused automaatselt."],
      ["Applications · Waiting lists · Notifications · Results", "Taotlused · Ootenimekirjad · Teavitused · Tulemused"],
      ["Dashboards, budgets<br>& reports", "Töölauad, eelarved<br>ja aruanded"],
      ["Keep deadlines, costs, results and warnings visible without rebuilding reports by hand.", "Hoiame tähtajad, kulud, tulemused ja hoiatused nähtaval ilma aruandeid käsitsi uuesti koostamata."],
      ["Live status · Clear ownership · Management overview", "Reaalaja olek · Selge vastutus · Juhtimisülevaade"],
      ["Documents<br>& communication", "Dokumendid<br>ja suhtlus"],
      ["Generate personalised emails, PDFs, certificates and organised records from the same data.", "Loome samadest andmetest isikupärastatud e-kirjad, PDF-id, sertifikaadid ja korrastatud kirjed."],
      ["Templates · Scheduled messages · Consistent records", "Mallid · Ajastatud sõnumid · Ühtsed kirjed"],
      ["Simple websites<br>& connected forms", "Lihtsad veebilehed<br>ja ühendatud vormid"],
      ["Create focused pages and forms that feed directly into the workflow behind them.", "Loome selged lehed ja vormid, mis suunavad andmed otse nende taga olevasse töövoogu."],
      ["Responsive pages · Useful forms · Reliable publishing", "Kohanduvad lehed · Kasulikud vormid · Usaldusväärne avaldamine"],
      ["One process, kept in sync", "Üks protsess, alati sünkroonis"],
      ["Enter the information once.<br>Use it everywhere.", "Sisesta info üks kord.<br>Kasuta seda kõikjal."],
      ["One form can update a table, notify the right person, create a document and keep a dashboard current — without copying the same information four times.", "Üks vorm võib uuendada tabelit, teavitada õiget inimest, luua dokumendi ja hoida töölaua ajakohasena — ilma sama infot neli korda kopeerimata."],
      ["Typical outcomes", "Tüüpilised tulemused"],
      ["Less copying", "Vähem kopeerimist"],
      ["Fewer missed steps", "Vähem vahelejäänud samme"],
      ["Clearer status", "Selgem ülevaade"],
      ["A connected automation example", "Ühendatud automatiseerimise näide"],
      ["Registration workflow", "Registreerimise töövoog"],
      ["4 connected steps", "4 ühendatud sammu"],
      ["Input", "Sisend"],
      ["Registration form", "Registreerimisvorm"],
      ["New response received", "Uus vastus saabus"],
      ["Record", "Kirje"],
      ["Working table", "Töötabel"],
      ["Status updated", "Olek uuendatud"],
      ["Action", "Tegevus"],
      ["Email + document", "E-kiri + dokument"],
      ["Created automatically", "Loodud automaatselt"],
      ["Overview", "Ülevaade"],
      ["Live dashboard", "Reaalajas töölaud"],
      ["Current and visible", "Ajakohane ja nähtav"],
      ["From bottleneck to working system.", "Kitsaskohast toimiva süsteemini."],
      ["No oversized transformation project. We start with the part of the work that will make the clearest difference.", "Ei mingit hiiglaslikku ümberkujundamisprojekti. Alustame töö osast, mis annab kõige selgema tulemuse."],
      ["Understand", "Mõistame"],
      ["We map what happens now, who is involved, and where the work gets stuck.", "Kaardistame praeguse töö, osalejad ja kohad, kus protsess takerdub."],
      ["Build", "Ehitame"],
      ["We create the smallest useful solution and test it with real information.", "Loome väikseima kasuliku lahenduse ja testime seda pärisandmetega."],
      ["Put it to work", "Võtame kasutusele"],
      ["We document the system, help the team use it, and improve what matters in everyday work.", "Dokumenteerime süsteemi, aitame tiimil seda kasutada ja täiustame igapäevatöös olulist."],
      ["Behind Vooglin", "Vooglini taga"],
      ["Your workflow,<br>handled personally.", "Sinu töövoog,<br>isiklikult juhitud."],
      ["You work directly with the person who maps, builds and improves your system. That keeps decisions clear, communication simple and every automation grounded in how your team actually works.", "Töötad otse inimesega, kes sinu süsteemi kaardistab, ehitab ja täiustab. Nii püsivad otsused selged, suhtlus lihtne ja iga automatiseerimine seotud sinu tiimi tegeliku tööga."],
      ["One point of contact, start to finish.", "Üks kontakt algusest lõpuni."],
      ["Practical systems, built around real work.", "Praktilised süsteemid, mis lähtuvad päris tööst."],
      ["Placeholder for the founder portrait", "Asutaja portree kohatäide"],
      ["Portrait / 4:5", "Portree / 4:5"],
      ["Your photo", "Sinu foto"],
      ["Add a vertical portrait here", "Lisa siia vertikaalne portree"],
      ["A process taking too much time?", "Kas mõni protsess võtab liiga palju aega?"],
      ["Let’s make it simpler.", "Teeme selle lihtsamaks."],
      ["Send us a short description of how it works today. We’ll help identify what can be automated and the sensible first step.", "Saada meile lühike kirjeldus sellest, kuidas töö täna käib. Aitame leida, mida saab automatiseerida ja milline on mõistlik esimene samm."],
      ["Start a conversation", "Alusta vestlust"],
    ],
    pricing: [
      ["Pricing — Clear scope and fixed quotes | Vooglin", "Hinnad — Selge töömaht ja fikseeritud pakkumine | Vooglin"],
      ["See how Vooglin prices automation and digital workflow projects. Every project receives a clear written scope and fixed quote before work begins.", "Vaata, kuidas Vooglin hinnastab automatiseerimise ja digitaalsete töövoogude projekte. Enne töö algust saad iga projekti kohta selge kirjaliku ulatuse ja fikseeritud pakkumise."],
      ["Clear scope. Fixed price before we build.", "Selge töömaht. Fikseeritud hind enne alustamist."],
      ["A transparent way to price practical automation and workflow projects.", "Läbipaistev viis praktiliste automatiseerimis- ja töövooprojektide hinnastamiseks."],
      ["Request a quote", "Küsi pakkumist"],
      ["Clear scope.<br>Fixed price before we build.", "Selge töömaht.<br>Fikseeritud hind enne alustamist."],
      ["Every project starts with a short review of the work, tools and desired result. You receive a written scope, delivery plan and fixed quote before any build begins.", "Iga projekt algab töö, tööriistade ja soovitud tulemuse lühikese ülevaatusega. Enne alustamist saad kirjaliku töömahu, teostusplaani ja fikseeritud pakkumise."],
      ["Discuss your workflow", "Räägime sinu töövoost"],
      ["No open-ended build. No surprise invoice.", "Ei mingit lahtise mahuga arendust. Ei mingeid üllatusarveid."],
      ["Project types", "Projektitüübid"],
      ["Priced around the work that needs to change.", "Hind lähtub tööst, mida on vaja muuta."],
      ["Focused improvement", "Konkreetne parendus"],
      ["One form, report, document process or repetitive task made simpler.", "Üks vorm, aruanne, dokumendiprotsess või korduv ülesanne tehakse lihtsamaks."],
      ["Fixed project quote", "Fikseeritud projektipakkumine"],
      ["Best for a clear, contained problem", "Sobib selge ja piiritletud probleemi jaoks"],
      ["Connected workflow", "Ühendatud töövoog"],
      ["Several tools and steps connected into one reliable day-to-day process.", "Mitu tööriista ja sammu ühendatakse üheks usaldusväärseks igapäevaprotsessiks."],
      ["Fixed scope + implementation", "Fikseeritud töömaht + teostus"],
      ["Best for work moving between people and systems", "Sobib tööle, mis liigub inimeste ja süsteemide vahel"],
      ["Ongoing support", "Jooksev tugi"],
      ["Small improvements, maintenance and new workflow needs after launch.", "Väikesed parendused, hooldus ja uued töövoovajadused pärast käivitamist."],
      ["Monthly or on demand", "Kuupõhiselt või vajaduse järgi"],
      ["Agreed before each period of work", "Lepime kokku enne iga tööperioodi"],
      ["Before the build", "Enne teostust"],
      ["You know the cost before work starts.", "Tead hinda enne töö algust."],
      ["Review", "Ülevaade"],
      ["We look at the current process, the people involved and the result you need.", "Vaatame üle praeguse protsessi, osalejad ja soovitud tulemuse."],
      ["Scope", "Töömaht"],
      ["We define what will be built, what access is required and what is outside the project.", "Määratleme, mida loome, millist ligipääsu on vaja ja mis jääb projektist välja."],
      ["Quote", "Pakkumine"],
      ["You receive the scope, delivery plan and fixed price in writing. Work begins only after you approve it.", "Saad töömahu, teostusplaani ja fikseeritud hinna kirjalikult. Töö algab alles pärast sinu kinnitust."],
      ["Pricing details", "Hinnastamise üksikasjad"],
      ["Pricing factors", "Hinda mõjutab"],
      ["The price depends on the workflow, not the size of your company.", "Hind sõltub töövoost, mitte ettevõtte suurusest."],
      ["Number of steps, tools and integrations", "Sammude, tööriistade ja integratsioonide arv"],
      ["Quality and structure of existing data", "Olemasolevate andmete kvaliteet ja struktuur"],
      ["User roles, permissions and approvals", "Kasutajarollid, õigused ja kinnitused"],
      ["Documents, messages and reports to generate", "Loodavad dokumendid, sõnumid ja aruanded"],
      ["Testing, documentation and handover", "Testimine, dokumentatsioon ja üleandmine"],
      ["Delivery urgency and support needs", "Teostuse kiirus ja toe vajadus"],
      ["Included", "Hinna sees"],
      ["A working system, clearly handed over.", "Toimiv süsteem ja selge üleandmine."],
      ["Agreed project scope", "Kokkulepitud projekti töömaht"],
      ["Build and integration work", "Arendus- ja integratsioonitöö"],
      ["Testing with realistic information", "Testimine realistlike andmetega"],
      ["Essential documentation", "Vajalik dokumentatsioon"],
      ["Handover and launch support", "Üleandmine ja käivitustugi"],
      ["Fixes for anything that does not match the agreed scope", "Parandused kõigele, mis ei vasta kokkulepitud töömahule"],
      ["Third-party costs", "Kolmandate osapoolte kulud"],
      ["Software costs stay visible.", "Tarkvarakulud jäävad nähtavaks."],
      ["Subscriptions, transaction fees, hosting and other third-party services are not hidden inside the project price. Any expected external costs are listed separately before you approve the work.", "Tellimused, tehingutasud, majutus ja muud kolmandate osapoolte teenused ei ole projektihinda peidetud. Kõik eeldatavad väliskulud tuuakse enne töö kinnitamist eraldi välja."],
      ["Have a process taking too much time?", "Kas mõni protsess võtab liiga palju aega?"],
      ["Let’s find the sensible first step.", "Leiame mõistliku esimese sammu."],
      ["Send a short description of how the work runs today. We’ll explain what should be simplified, what the project would include and what it would cost.", "Saada lühike kirjeldus sellest, kuidas töö täna käib. Selgitame, mida tasub lihtsustada, mida projekt sisaldaks ja kui palju see maksaks."],
      ["Request a project quote", "Küsi projektipakkumist"],
    ],
  },
  ru: {
    common: [
      ["Skip to content", "Перейти к содержанию"],
      ["Vooglin home", "Главная Vooglin"],
      ["Primary navigation", "Основная навигация"],
      ["Mobile navigation", "Мобильная навигация"],
      ["Language", "Язык"],
      ["Services", "Услуги"],
      ["How it works", "Как это работает"],
      ["Pricing", "Цены"],
      ["About", "О нас"],
      ["Contact", "Контакты"],
      ["Menu", "Меню"],
      ["Close", "Закрыть"],
      ["Practical automation and digital workflows for small organisations and project teams.", "Практичная автоматизация и цифровые процессы для небольших организаций и проектных команд."],
      ["All rights reserved.", "Все права защищены."],
      ["Back to top", "Наверх"],
    ],
    home: [
      ["Vooglin — Practical automation for everyday work", "Vooglin — Практичная автоматизация повседневной работы"],
      ["Vooglin builds practical automation and digital workflows for small organisations, project teams, and growing businesses.", "Vooglin создаёт практичные решения для автоматизации и цифровые процессы для небольших организаций, проектных команд и растущего бизнеса."],
      ["Automate the work that slows you down.", "Автоматизируйте работу, которая вас замедляет."],
      ["Practical automation and digital workflows for small organisations and project teams.", "Практичная автоматизация и цифровые процессы для небольших организаций и проектных команд."],
      ["Discuss your workflow", "Обсудить ваш процесс"],
      ["Practical automation for small teams", "Практичная автоматизация для небольших команд"],
      ["Vooglin turns forms, spreadsheets, emails and documents into clear workflows that run with less manual effort.", "Vooglin объединяет формы, таблицы, письма и документы в понятные процессы, которым требуется меньше ручной работы."],
      ["An example Vooglin workflow", "Пример процесса Vooglin"],
      ["A typical workflow", "Типичный процесс"],
      ["Connected", "Подключено"],
      ["Collect", "Собрать"],
      ["Forms, email and files", "Формы, почта и файлы"],
      ["Organise", "Упорядочить"],
      ["Rules, ownership and status", "Правила, ответственные и статусы"],
      ["Act", "Выполнить"],
      ["Documents, reminders and tasks", "Документы, напоминания и задачи"],
      ["See", "Следить"],
      ["Dashboards, reports and next steps", "Панели, отчёты и следующие шаги"],
      ["One workflow. Fewer handovers.", "Один процесс. Меньше передач между людьми."],
      ["Built for small organisations, project teams, events and growing businesses.", "Для небольших организаций, проектных команд, мероприятий и растущего бизнеса."],
      ["Based in Estonia · Working digitally", "Работаем из Эстонии · Полностью онлайн"],
      ["A simpler way to work", "Более простой способ работать"],
      ["Built around your process.<br>Not around a platform.", "Создано вокруг вашего процесса,<br>а не вокруг платформы."],
      ["We find the repeated steps, connect the tools you already use, and build only what the work needs.", "Мы находим повторяющиеся шаги, соединяем уже используемые инструменты и создаём только то, что действительно нужно работе."],
      ["How Vooglin works", "Как работает Vooglin"],
      ["Practical by design", "Практично по замыслу"],
      ["Every part of the system has a clear job.", "У каждой части системы есть понятная задача."],
      ["Easy to understand", "Легко понять"],
      ["Your team can see how it works and use it with confidence.", "Команда понимает, как всё устроено, и уверенно пользуется системой."],
      ["Ready to improve", "Готово к развитию"],
      ["Start with the useful core, then grow it when the work changes.", "Начинаем с полезной основы и развиваем её вместе с изменениями в работе."],
      ["Systems that remove repetitive work.", "Системы, которые избавляют от повторяющейся работы."],
      ["From one troublesome process to a connected day-to-day system.", "От одного неудобного процесса до связанной повседневной системы."],
      ["Workflow automation<br>& integrations", "Автоматизация процессов<br>и интеграции"],
      ["Connect forms, spreadsheets, email, documents and task tools into one reliable flow.", "Объединяем формы, таблицы, почту, документы и задачи в один надёжный процесс."],
      ["Forms, registrations<br>& events", "Формы, регистрации<br>и мероприятия"],
      ["Collect applications, manage limits and statuses, and send confirmations and reminders automatically.", "Собираем заявки, управляем лимитами и статусами, автоматически отправляем подтверждения и напоминания."],
      ["Applications · Waiting lists · Notifications · Results", "Заявки · Листы ожидания · Уведомления · Результаты"],
      ["Dashboards, budgets<br>& reports", "Панели, бюджеты<br>и отчёты"],
      ["Keep deadlines, costs, results and warnings visible without rebuilding reports by hand.", "Держим сроки, расходы, результаты и предупреждения на виду без ручной пересборки отчётов."],
      ["Live status · Clear ownership · Management overview", "Актуальный статус · Ответственные · Обзор для руководителя"],
      ["Documents<br>& communication", "Документы<br>и коммуникация"],
      ["Generate personalised emails, PDFs, certificates and organised records from the same data.", "Создаём персональные письма, PDF, сертификаты и упорядоченные записи из одних и тех же данных."],
      ["Templates · Scheduled messages · Consistent records", "Шаблоны · Отложенные сообщения · Единые записи"],
      ["Simple websites<br>& connected forms", "Простые сайты<br>и связанные формы"],
      ["Create focused pages and forms that feed directly into the workflow behind them.", "Создаём понятные страницы и формы, которые сразу передают данные в связанный процесс."],
      ["Responsive pages · Useful forms · Reliable publishing", "Адаптивные страницы · Полезные формы · Надёжная публикация"],
      ["One process, kept in sync", "Один процесс, всегда синхронизирован"],
      ["Enter the information once.<br>Use it everywhere.", "Введите данные один раз.<br>Используйте их везде."],
      ["One form can update a table, notify the right person, create a document and keep a dashboard current — without copying the same information four times.", "Одна форма может обновить таблицу, уведомить нужного человека, создать документ и поддерживать панель в актуальном состоянии — без четырёхкратного копирования данных."],
      ["Typical outcomes", "Обычный результат"],
      ["Less copying", "Меньше копирования"],
      ["Fewer missed steps", "Меньше пропущенных шагов"],
      ["Clearer status", "Понятнее статус"],
      ["A connected automation example", "Пример связанной автоматизации"],
      ["Registration workflow", "Процесс регистрации"],
      ["4 connected steps", "4 связанных шага"],
      ["Input", "Ввод"],
      ["Registration form", "Форма регистрации"],
      ["New response received", "Получен новый ответ"],
      ["Record", "Запись"],
      ["Working table", "Рабочая таблица"],
      ["Status updated", "Статус обновлён"],
      ["Action", "Действие"],
      ["Email + document", "Письмо + документ"],
      ["Created automatically", "Создано автоматически"],
      ["Overview", "Обзор"],
      ["Live dashboard", "Актуальная панель"],
      ["Current and visible", "Актуально и наглядно"],
      ["From bottleneck to working system.", "От узкого места к работающей системе."],
      ["No oversized transformation project. We start with the part of the work that will make the clearest difference.", "Без огромного проекта по перестройке всего. Начинаем с той части работы, где результат будет самым заметным."],
      ["Understand", "Разбираемся"],
      ["We map what happens now, who is involved, and where the work gets stuck.", "Разбираем текущий процесс, участников и места, где работа застревает."],
      ["Build", "Создаём"],
      ["We create the smallest useful solution and test it with real information.", "Создаём минимальное полезное решение и проверяем его на реальных данных."],
      ["Put it to work", "Запускаем в работу"],
      ["We document the system, help the team use it, and improve what matters in everyday work.", "Документируем систему, помогаем команде начать работу и улучшаем то, что важно каждый день."],
      ["Behind Vooglin", "Кто стоит за Vooglin"],
      ["Your workflow,<br>handled personally.", "Ваш процесс —<br>под личным контролем."],
      ["You work directly with the person who maps, builds and improves your system. That keeps decisions clear, communication simple and every automation grounded in how your team actually works.", "Вы напрямую работаете с человеком, который изучает, создаёт и улучшает вашу систему. Решения остаются понятными, общение — простым, а автоматизация соответствует реальной работе команды."],
      ["One point of contact, start to finish.", "Один контакт от начала до конца."],
      ["Practical systems, built around real work.", "Практичные системы для реальной работы."],
      ["Placeholder for the founder portrait", "Место для портрета основателя"],
      ["Portrait / 4:5", "Портрет / 4:5"],
      ["Your photo", "Ваше фото"],
      ["Add a vertical portrait here", "Добавьте сюда вертикальный портрет"],
      ["A process taking too much time?", "Какой-то процесс отнимает слишком много времени?"],
      ["Let’s make it simpler.", "Давайте сделаем его проще."],
      ["Send us a short description of how it works today. We’ll help identify what can be automated and the sensible first step.", "Коротко опишите, как всё работает сейчас. Мы поможем определить, что можно автоматизировать и с чего разумно начать."],
      ["Start a conversation", "Начать разговор"],
    ],
    pricing: [
      ["Pricing — Clear scope and fixed quotes | Vooglin", "Цены — Понятный объём и фиксированная стоимость | Vooglin"],
      ["See how Vooglin prices automation and digital workflow projects. Every project receives a clear written scope and fixed quote before work begins.", "Узнайте, как Vooglin оценивает проекты автоматизации и цифровых процессов. До начала работы вы получаете понятный письменный объём и фиксированную стоимость."],
      ["Clear scope. Fixed price before we build.", "Понятный объём. Фиксированная цена до начала работ."],
      ["A transparent way to price practical automation and workflow projects.", "Прозрачная оценка проектов практичной автоматизации и рабочих процессов."],
      ["Request a quote", "Запросить расчёт"],
      ["Clear scope.<br>Fixed price before we build.", "Понятный объём.<br>Фиксированная цена до начала работ."],
      ["Every project starts with a short review of the work, tools and desired result. You receive a written scope, delivery plan and fixed quote before any build begins.", "Каждый проект начинается с короткого разбора работы, инструментов и желаемого результата. До начала создания вы получаете письменный объём, план реализации и фиксированную стоимость."],
      ["Discuss your workflow", "Обсудить ваш процесс"],
      ["No open-ended build. No surprise invoice.", "Никаких работ с открытым бюджетом. Никаких неожиданных счетов."],
      ["Project types", "Типы проектов"],
      ["Priced around the work that needs to change.", "Стоимость зависит от работы, которую нужно изменить."],
      ["Focused improvement", "Точечное улучшение"],
      ["One form, report, document process or repetitive task made simpler.", "Упрощаем одну форму, отчёт, процесс с документами или повторяющуюся задачу."],
      ["Fixed project quote", "Фиксированная стоимость проекта"],
      ["Best for a clear, contained problem", "Для понятной и ограниченной задачи"],
      ["Connected workflow", "Связанный процесс"],
      ["Several tools and steps connected into one reliable day-to-day process.", "Несколько инструментов и шагов объединяются в один надёжный повседневный процесс."],
      ["Fixed scope + implementation", "Фиксированный объём + реализация"],
      ["Best for work moving between people and systems", "Для работы, которая переходит между людьми и системами"],
      ["Ongoing support", "Постоянная поддержка"],
      ["Small improvements, maintenance and new workflow needs after launch.", "Небольшие улучшения, обслуживание и новые задачи после запуска."],
      ["Monthly or on demand", "Ежемесячно или по запросу"],
      ["Agreed before each period of work", "Согласовывается перед каждым периодом работ"],
      ["Before the build", "До начала создания"],
      ["You know the cost before work starts.", "Вы знаете стоимость до начала работ."],
      ["Review", "Разбор"],
      ["We look at the current process, the people involved and the result you need.", "Изучаем текущий процесс, его участников и нужный вам результат."],
      ["Scope", "Объём"],
      ["We define what will be built, what access is required and what is outside the project.", "Определяем, что будет создано, какие доступы нужны и что не входит в проект."],
      ["Quote", "Расчёт"],
      ["You receive the scope, delivery plan and fixed price in writing. Work begins only after you approve it.", "Вы письменно получаете объём, план реализации и фиксированную цену. Работа начинается только после вашего подтверждения."],
      ["Pricing details", "Детали ценообразования"],
      ["Pricing factors", "На цену влияют"],
      ["The price depends on the workflow, not the size of your company.", "Цена зависит от процесса, а не от размера компании."],
      ["Number of steps, tools and integrations", "Количество шагов, инструментов и интеграций"],
      ["Quality and structure of existing data", "Качество и структура существующих данных"],
      ["User roles, permissions and approvals", "Роли пользователей, права и согласования"],
      ["Documents, messages and reports to generate", "Документы, сообщения и отчёты, которые нужно создавать"],
      ["Testing, documentation and handover", "Тестирование, документация и передача"],
      ["Delivery urgency and support needs", "Срочность реализации и потребность в поддержке"],
      ["Included", "Включено"],
      ["A working system, clearly handed over.", "Готовая система и понятная передача команде."],
      ["Agreed project scope", "Согласованный объём проекта"],
      ["Build and integration work", "Создание и интеграция"],
      ["Testing with realistic information", "Тестирование на реалистичных данных"],
      ["Essential documentation", "Необходимая документация"],
      ["Handover and launch support", "Передача и поддержка запуска"],
      ["Fixes for anything that does not match the agreed scope", "Исправления всего, что не соответствует согласованному объёму"],
      ["Third-party costs", "Расходы на сторонние сервисы"],
      ["Software costs stay visible.", "Расходы на сервисы остаются прозрачными."],
      ["Subscriptions, transaction fees, hosting and other third-party services are not hidden inside the project price. Any expected external costs are listed separately before you approve the work.", "Подписки, комиссии, хостинг и другие сторонние сервисы не скрываются в цене проекта. Все ожидаемые внешние расходы указываются отдельно до вашего подтверждения."],
      ["Have a process taking too much time?", "Какой-то процесс отнимает слишком много времени?"],
      ["Let’s find the sensible first step.", "Давайте найдём разумный первый шаг."],
      ["Send a short description of how the work runs today. We’ll explain what should be simplified, what the project would include and what it would cost.", "Коротко опишите, как работа устроена сейчас. Мы объясним, что стоит упростить, что войдёт в проект и сколько это будет стоить."],
      ["Request a project quote", "Запросить расчёт проекта"],
    ],
  },
};

function replaceAll(source, pairs) {
  return [...pairs]
    .sort(([left], [right]) => right.length - left.length)
    .reduce((result, [from, to]) => result.split(from).join(to), source);
}

function languageSwitcher(locale, page) {
  const pricing = page === "pricing" ? "pricing/" : "";
  const links = [
    ["en", `/${pricing}`, "EN"],
    ["et", `/et/${pricing}`, "ET"],
    ["ru", `/ru/${pricing}`, "RU"],
  ];

  return links.map(([code, href, label]) =>
    `<a href="${href}" lang="${code}" hreflang="${code}"${code === locale ? ' aria-current="page"' : ""}>${label}</a>`
  ).join("\n          ");
}

export function localizePage(source, locale, page) {
  const dictionary = translations[locale];
  let html = source;
  const basePath = `/${locale}/`;
  const pagePath = page === "pricing" ? `${basePath}pricing/` : basePath;

  html = html.replace('<html lang="en">', `<html lang="${locale}">`);
  html = html.replace(/https:\/\/vooglin\.ee\/pricing\//g, `https://vooglin.ee${basePath}pricing/`);
  if (page === "home") {
    html = html.replace(/https:\/\/vooglin\.ee\/(?!og-brand\.png|favicon\.png)/g, `https://vooglin.ee${basePath}`);
    html = html.replace(/href="\/pricing\/"/g, `href="${basePath}pricing/"`);
  } else {
    html = html.replace(/href="\/#([a-z-]+)"/g, `href="${basePath}#$1"`);
    html = html.replace(/href="\/"/g, `href="${basePath}"`);
  }

  html = html.replace(
    /<nav class="language-switcher" aria-label="Language">[\s\S]*?<\/nav>/,
    `<nav class="language-switcher" aria-label="Language">\n          ${languageSwitcher(locale, page)}\n        </nav>`
  );
  html = html.replace(
    /<div class="mobile-language-switcher language-switcher" aria-label="Language">[\s\S]*?<\/div>/,
    `<div class="mobile-language-switcher language-switcher" aria-label="Language">\n        ${languageSwitcher(locale, page)}\n      </div>`
  );

  html = html.replace(/<link rel="canonical" href="[^"]+">/, `<link rel="canonical" href="https://vooglin.ee${pagePath}">`);
  html = html.replace(/<meta property="og:url" content="[^"]+">/, `<meta property="og:url" content="https://vooglin.ee${pagePath}">`);
  const pricingSuffix = page === "pricing" ? "pricing/" : "";
  html = html.replace(
    /  <link rel="alternate" hreflang="en"[^>]+>\n  <link rel="alternate" hreflang="et"[^>]+>\n  <link rel="alternate" hreflang="ru"[^>]+>\n  <link rel="alternate" hreflang="x-default"[^>]+>/,
    `  <link rel="alternate" hreflang="en" href="https://vooglin.ee/${pricingSuffix}">\n` +
    `  <link rel="alternate" hreflang="et" href="https://vooglin.ee/et/${pricingSuffix}">\n` +
    `  <link rel="alternate" hreflang="ru" href="https://vooglin.ee/ru/${pricingSuffix}">\n` +
    `  <link rel="alternate" hreflang="x-default" href="https://vooglin.ee/${pricingSuffix}">`
  );
  html = replaceAll(html, [...dictionary.home.filter(() => page === "home"), ...dictionary.pricing.filter(() => page === "pricing"), ...dictionary.common]);
  html = html.replace(
    /data-menu-label="[^"]+" data-close-label="[^"]+"/,
    `data-menu-label="${locale === "et" ? "Menüü" : "Меню"}" data-close-label="${locale === "et" ? "Sulge" : "Закрыть"}"`
  );

  return html;
}
